version: '3'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - TZ=GMT
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bookstoreapi:
    build: .
    container_name: bookstoreapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_NAME=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres
    ports:
      - "8081:8081"

volumes:
  postgres_data:
