version: '3.7'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - TZ=GMT
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: